version: '3'
services: 
    hhvm:
        build: .
        volumes: 
            - .:/var/www/
            # - ./config/server.ini:/etc/hhvm/server.ini
        ports:
            - 80:80
        depends_on: 
            - db
    db:
        container_name: mysql8
        image: mysql:latest
        command:
            --default-authentication-plugin=mysql_native_password
        restart: always
        volumes: 
            - ./schemas/wbengine_skeletone_app_mysql_template.sql:/docker-entrypoint-initdb.d/wbengine_skeletone_app_mysql_template.sql
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: wbengine_skeleton_app
            MYSQL_USER: dev_user
            MYSQL_PASSWORD: dev_password
        ports:
            - 3306:3306            